---
title: "Reto"
author: "Equipo 4: José Derbez, Federico Medina, Eduardo Porcayo, Javier Hernández, Karen Ugalde"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide'}

library(MASS)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(corrplot)
library(lmtest)
library(plotrix)
library(klaR)
library(lattice)
library(caret)

datos <- read.csv('clasificacion_no_na.csv',
                      header=TRUE, stringsAsFactors=FALSE)
datos
attach(datos)
```

```{r}
datos$NormativaPromedio <- factor(datos$NormativaPromedio, levels=c(0,1), labels=c("Cumplimiento", "Incumplimiento"))
str(datos)
prop.table(table(datos$NormativaPromedio))
```




```{r}


modelo <- lda(NormativaPromedio ~ . , datos)
str(modelo)
```

```{r}
modelo
```

```{r}
datos$Disc <- 0.063*PM2 + SO2 * (-0.0015254745) + O3  * (-0.0005542200) + CO  *  (0.0001067325) + T   * (-0.0498351378) + RH  * (-0.0325632219) + SR  * (-1.4306596033) + RF  * (-0.0079615084) + PRS * (-0.0373525325) + WS  * (-0.0083289883)
mean(datos$Disc)
```

```{r}
tapply(datos$Disc, datos$NormativaPromedio, mean)
```

```{r, results=FALSE}
c3 <- (-29.471 - 28.359)/2; c3

datos$classP3 <- ifelse(datos$Disc > c3, 1, 0)
datos$classP3 <- factor(datos$classP3, levels = c(0,1), labels = c("Cumplimiento", "Incumplimiento"))
datos
```

```{r}
table(Valores_Reales = datos$NormativaPromedio, Valores_Pred = datos$classP3)
```

```{r}
# Accuracy
mean(datos$NormativaPromedio == datos$classP3)
```
```{r}
# Recall para incumplimiento

print(round(2481/8329, 4))
```



```{r}
library(ggplot2)
ggplot(datos) + aes(x = Disc, fill = NormativaPromedio) + geom_histogram(position = "identity") +
  geom_vline(xintercept = c3, linetype = "longdash") +
  scale_x_continuous(breaks = seq(-5, 5, 1))
```

```{r, results='hide'}
datos$dif <- datos$Disc - c3
datos$dif
```

```{r}
predicciones <- predict(modelo)
str(predicciones)
```

```{r}
ggplot(datos) + aes(x = dif, fill = NormativaPromedio) + geom_histogram(position = "identity") +
  geom_vline(xintercept = c3, linetype = "longdash") +
  scale_x_continuous(breaks = seq(-5, 5, 1))
```

```{r, results='hide'}
datos$prob <- predicciones$posterior[,2]
predicciones$class
```

```{r}
ggplot(datos) + aes(x = prob, color = NormativaPromedio, fill = NormativaPromedio) + 
  geom_density(alpha = 0.3) + theme_bw() +
  geom_vline(xintercept = 0.5)
```

# PCA

```{r}

library(dplyr)
library(psych)
library(GGally)
library(ggplot2)
library(gridExtra)
library(corrplot)
library(car)
library(dplyr)
library(lmtest)

datos <- read.csv("datos/clean_df.csv")
#datos
df = na.omit(datos)
df1 = df[2:12]

apply(X = df1, MARGIN = 2, FUN = mean)
apply(X = df1, MARGIN = 2, FUN = var)

pca <- prcomp(df1, scale = TRUE)
names(pca)

#pca$center
#pca$scale

pca$rotation
head(pca$x)

#dim(pca$x)
biplot(x = pca, scale = 0, cex = 0.6, col = c("blue4", "brown3"))

pca$rotation <- -pca$rotation
pca$x        <- -pca$x
biplot(x = pca, scale = 0, cex = 0.6, col = c("blue4", "brown3"))

pca$sdev^2

prop_varianza <- pca$sdev^2 / sum(pca$sdev^2)
prop_varianza

ggplot(data = data.frame(prop_varianza, pc = 1:11),
       aes(x = pc, y = prop_varianza)) +
  geom_col(width = 0.3) +
  scale_y_continuous(limits = c(0,1)) +
  theme_bw() +
  labs(x = "Componente principal",
       y = "Prop. de varianza explicada")

prop_varianza_acum <- cumsum(prop_varianza)
prop_varianza_acum

ggplot(data = data.frame(prop_varianza_acum, pc = 1:11),
       aes(x = pc, y = prop_varianza_acum, group = 1)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(x = "Componente principal",
       y = "Prop. varianza explicada acumulada")

```

